#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("RecyclerViewer.Resource", IsApplication=true)]

namespace RecyclerViewer
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Corcav.SmartRecyclerViewAdapter.Resource.Attribute.layoutManager = global::RecyclerViewer.Resource.Attribute.layoutManager;
			global::Corcav.SmartRecyclerViewAdapter.Resource.Attribute.reverseLayout = global::RecyclerViewer.Resource.Attribute.reverseLayout;
			global::Corcav.SmartRecyclerViewAdapter.Resource.Attribute.spanCount = global::RecyclerViewer.Resource.Attribute.spanCount;
			global::Corcav.SmartRecyclerViewAdapter.Resource.Attribute.stackFromEnd = global::RecyclerViewer.Resource.Attribute.stackFromEnd;
			global::Corcav.SmartRecyclerViewAdapter.Resource.Dimension.item_touch_helper_max_drag_scroll_per_frame = global::RecyclerViewer.Resource.Dimension.item_touch_helper_max_drag_scroll_per_frame;
			global::Corcav.SmartRecyclerViewAdapter.Resource.Dimension.item_touch_helper_swipe_escape_max_velocity = global::RecyclerViewer.Resource.Dimension.item_touch_helper_swipe_escape_max_velocity;
			global::Corcav.SmartRecyclerViewAdapter.Resource.Dimension.item_touch_helper_swipe_escape_velocity = global::RecyclerViewer.Resource.Dimension.item_touch_helper_swipe_escape_velocity;
			global::Corcav.SmartRecyclerViewAdapter.Resource.Id.item_touch_helper_previous_elevation = global::RecyclerViewer.Resource.Id.item_touch_helper_previous_elevation;
			global::Corcav.SmartRecyclerViewAdapter.Resource.String.ApplicationName = global::RecyclerViewer.Resource.String.ApplicationName;
			global::Corcav.SmartRecyclerViewAdapter.Resource.String.Hello = global::RecyclerViewer.Resource.String.Hello;
			global::Corcav.SmartRecyclerViewAdapter.Resource.Styleable.RecyclerView = global::RecyclerViewer.Resource.Styleable.RecyclerView;
			global::Corcav.SmartRecyclerViewAdapter.Resource.Styleable.RecyclerView_android_orientation = global::RecyclerViewer.Resource.Styleable.RecyclerView_android_orientation;
			global::Corcav.SmartRecyclerViewAdapter.Resource.Styleable.RecyclerView_layoutManager = global::RecyclerViewer.Resource.Styleable.RecyclerView_layoutManager;
			global::Corcav.SmartRecyclerViewAdapter.Resource.Styleable.RecyclerView_reverseLayout = global::RecyclerViewer.Resource.Styleable.RecyclerView_reverseLayout;
			global::Corcav.SmartRecyclerViewAdapter.Resource.Styleable.RecyclerView_spanCount = global::RecyclerViewer.Resource.Styleable.RecyclerView_spanCount;
			global::Corcav.SmartRecyclerViewAdapter.Resource.Styleable.RecyclerView_stackFromEnd = global::RecyclerViewer.Resource.Styleable.RecyclerView_stackFromEnd;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010004
			public const int cardBackgroundColor = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int cardCornerRadius = 2130771973;
			
			// aapt resource value: 0x7f010006
			public const int cardElevation = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int cardMaxElevation = 2130771975;
			
			// aapt resource value: 0x7f010009
			public const int cardPreventCornerOverlap = 2130771977;
			
			// aapt resource value: 0x7f010008
			public const int cardUseCompatPadding = 2130771976;
			
			// aapt resource value: 0x7f01000a
			public const int contentPadding = 2130771978;
			
			// aapt resource value: 0x7f01000e
			public const int contentPaddingBottom = 2130771982;
			
			// aapt resource value: 0x7f01000b
			public const int contentPaddingLeft = 2130771979;
			
			// aapt resource value: 0x7f01000c
			public const int contentPaddingRight = 2130771980;
			
			// aapt resource value: 0x7f01000d
			public const int contentPaddingTop = 2130771981;
			
			// aapt resource value: 0x7f010000
			public const int layoutManager = 2130771968;
			
			// aapt resource value: 0x7f010002
			public const int reverseLayout = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int spanCount = 2130771969;
			
			// aapt resource value: 0x7f010003
			public const int stackFromEnd = 2130771971;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060000
			public const int cardview_dark_background = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int cardview_light_background = 2131099649;
			
			// aapt resource value: 0x7f060002
			public const int cardview_shadow_end_color = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int cardview_shadow_start_color = 2131099651;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040003
			public const int cardview_compat_inset_shadow = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int cardview_default_elevation = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int cardview_default_radius = 2130968581;
			
			// aapt resource value: 0x7f040000
			public const int item_touch_helper_max_drag_scroll_per_frame = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int item_touch_helper_swipe_escape_max_velocity = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int item_touch_helper_swipe_escape_velocity = 2130968578;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arc_de_triomphe = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int before_mobile_phones = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int big_ben_1 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int big_ben_2 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int buckingham_guards = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int champ_elysees = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int downtown_edinburgh = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int edinburgh_castle_1 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int edinburgh_castle_2 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int edinburgh_from_on_high = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int edinburgh_station = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int eurostar = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int heres_lookin_at_ya = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int Icon = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int inside_notre_dame = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int la_tour_eiffel = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int london_eye = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int louvre_1 = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int louvre_2 = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int medieval_siege_gun = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int modest_accomodations = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int museum_and_castle = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int notre_dame = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int old_meets_new = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int one_o_clock_gun = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int pompidou_centre = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int portcullis_gate = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int royal_mile = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int rue_cler = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int scott_monument = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int seine_barge = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int seine_river = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int to_notre_dame = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int tower_of_london = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int tower_visitors = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int versailles_fountains = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int versailles_gates = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int victoria_albert = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int view_from_holyrood_park = 2130837542;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050003
			public const int imageView = 2131034115;
			
			// aapt resource value: 0x7f050000
			public const int item_touch_helper_previous_elevation = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int randPickButton = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int recyclerView = 2131034114;
			
			// aapt resource value: 0x7f050004
			public const int textView = 2131034116;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int PhotoCardView = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f080001
			public const int ApplicationName = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int Hello = 2131230720;
			
			// aapt resource value: 0x7f080003
			public const int app_name = 2131230723;
			
			// aapt resource value: 0x7f080002
			public const int hello = 2131230722;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f070000
			public const int Base_CardView = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int CardView = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int CardView_Dark = 2131165186;
			
			// aapt resource value: 0x7f070003
			public const int CardView_Light = 2131165187;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] CardView = new int[] {
					16843071,
					16843072,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981,
					2130771982};
			
			// aapt resource value: 1
			public const int CardView_android_minHeight = 1;
			
			// aapt resource value: 0
			public const int CardView_android_minWidth = 0;
			
			// aapt resource value: 2
			public const int CardView_cardBackgroundColor = 2;
			
			// aapt resource value: 3
			public const int CardView_cardCornerRadius = 3;
			
			// aapt resource value: 4
			public const int CardView_cardElevation = 4;
			
			// aapt resource value: 5
			public const int CardView_cardMaxElevation = 5;
			
			// aapt resource value: 7
			public const int CardView_cardPreventCornerOverlap = 7;
			
			// aapt resource value: 6
			public const int CardView_cardUseCompatPadding = 6;
			
			// aapt resource value: 8
			public const int CardView_contentPadding = 8;
			
			// aapt resource value: 12
			public const int CardView_contentPaddingBottom = 12;
			
			// aapt resource value: 9
			public const int CardView_contentPaddingLeft = 9;
			
			// aapt resource value: 10
			public const int CardView_contentPaddingRight = 10;
			
			// aapt resource value: 11
			public const int CardView_contentPaddingTop = 11;
			
			public static int[] RecyclerView = new int[] {
					16842948,
					2130771968,
					2130771969,
					2130771970,
					2130771971};
			
			// aapt resource value: 0
			public const int RecyclerView_android_orientation = 0;
			
			// aapt resource value: 1
			public const int RecyclerView_layoutManager = 1;
			
			// aapt resource value: 3
			public const int RecyclerView_reverseLayout = 3;
			
			// aapt resource value: 2
			public const int RecyclerView_spanCount = 2;
			
			// aapt resource value: 4
			public const int RecyclerView_stackFromEnd = 4;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
